### PR TITLE
[CD-3129] Create a Typescript/React project

### PR DESCRIPTION
**Pull request by SuperCoolFrog**
[CD-3129] Create a Typescript/React project with everything needed to get started including:

- building
- running locally
- linting
- testing

[CD-3129]

[CD-3129]: https://vertexsmb.atlassian.net/browse/CD-3129
[CD-3129]: https://vertexsmb.atlassian.net/browse/CD-3129

### CODE REVIEW

**Comment by mkgallelli** [comment]
I noticed that we are targeting ES6.  Lets check up on what version OSERIES team is targeting.  While our Wizard project must target the widest possible user base within reason, internally that does not necessarily need to be the case.

**Comment by mkgallelli** [comment]
It looks like we're cutting babel out of our tool chain.  Take a look at -->  https://iamturns.com/typescript-babel/  Let me know what you think.  It may simplify things early on, however having Babel in our toolh chain can lead to some very powerful optimizations later on.  Chris Krycho recommends using TSC for type checking (linting) followed by Babel transpilation on the co-recursive podcast.

**Comment by mkgallelli** [comment]
Also, this is pretty awesome!  Great job!

**Comment by SuperCoolFrog** [comment]
> It looks like we're cutting babel out of our tool chain. Take a look at --> https://iamturns.com/typescript-babel/ Let me know what you think. It may simplify things early on, however having Babel in our toolh chain can lead to some very powerful optimizations later on. Chris Krycho recommends using TSC for type checking (linting) followed by Babel transpilation on the co-recursive podcast. https://corecursive.com/034-chris-krycho-typescript/

Added babel

**Pull request closed without merging**
